name: Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Change to project directory
      run: cd roman-number

    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: '11'
        distribution: 'adopt'
        java-package: 'jdk'
        architecture: 'x64'
        check-latest: false
        server-id: 'github'
        server-username: ${{ github.actor }}
        server-password: ${{ secrets.GITHUB_TOKEN }}
        overwrite-settings: true
        job-status: 'success'

    - name: Build and test with coverage
      run: |
        mvn clean verify jacoco:report

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: target/site/jacoco/index.html



