name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 8.0.332+9
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B install --file roman-number/pom.xml





