name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Change to project directory
      run: cd roman-number/pom.xml

    - name: Build with Maven
      run: mvn clean install

