name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8.0.332+9
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B clean install --file roman-number/pom.xml

      - name: Test
        run: mvn test --file roman-number/pom.xml
        
      - name: Create site
        run: mvn site --file roman-number/pom.xml
        
      - name: Run tests
        run: mvn test --file roman-number/pom.xml

      - name: Generate JaCoCo coverage report
        run: mvn jacoco:report --file roman-number/pom.xml

      - name: Send coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.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 }}
          path-to-lcov: roman-number/target/site/jacoco/jacoco.xml
